language: node_js
node_js:
  - 10
addons:
  apt:
    packages:
      - xvfb

notifications:
  slack: ser515team:yyeZIHSbcSTRNfwPcMnjigHz

before_script:
  - npm install -g electron-forge
  - npm install
script:
  - npm run travis
