language: node_js

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

notifications:
  slack: ser515team:yyeZIHSbcSTRNfwPcMnjigHz

before_script:
  - npm install -g npm@^4.1.5
  - npm install

script:
  - npm travis